class

diff --git a/10-Install-shell-script b/10-Install-shell-script
--- a/10-Install-shell-script
+++ b/10-Install-shell-script
@@ -8,6 +8,36 @@ then
     exit 1 #other than 0
 fi
 
-#dnf list installed mysql
+dnf list installed mysql
 
-echo "Hello"
+if [ $? -ne 0 ]
+then # not installed
+    dnf install mysql -y # command to instal Mysql
+    if [ $? -ne 0 ]
+    then
+        echo "Installing MySQL ... FAILURE"
+        exit 1
+    else
+        echo "Installing MySQL ... SUCCESS"
+    fi
+else
+    echo "MySQL is already ... INSTALLED"
+fi
+
+
+
+dnf list installed git
+
+if [ $? -ne 0 ]
+then
+    dnf install git -y # command to instal Git
+    if [ $? -ne 0 ]
+    then
+        echo "Installing Git ... FAILURE"
+        exit 1
+    else
+        echo "Installing Git ... SUCCESS"
+    fi
+else
+    echo "Git is already ... INSTALLED"
+fi
